# Copyright (c) 2019 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: octant
  labels:
    app: octant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octant
  template:
    metadata:
      labels:
        app: octant
    spec:
      containers:
      - name: octant
        image: octant
        command: ["/octant"]
        args: ["-v", "--kubeconfig", "/kube/dev-dash-kubeconfig.yaml"]
        ports:
        - containerPort: 7777
        env:
          - name: OCTANT_LISTENER_ADDR
            value: 0.0.0.0:7777
          - name: OCTANT_DISABLE_OPEN_BROWSER
            value: "1"
        volumeMounts:
          - name: kubeconfig
            mountPath: /kube/
      volumes:
        - name: kubeconfig
          secret:
            secretName: octant-kubeconfig
            defaultMode: 256
