# Copyright (c) 2019 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

resources:
  - deployment.yaml

images:
  - name: octant
    newName: harbor.bryanl.dev/test/octant
    newTag: latest
